plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.johnrengelman.shadow' version '8.1.1' // Add this line
}

group = 'org.pucmm.practica'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.2'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.1'
    implementation 'org.postgresql:postgresql:42.7.3'
    implementation 'com.google.code.gson:gson:2.10.1' // Actualizado
    implementation 'com.zaxxer:HikariCP:5.0.1'
    implementation 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'  // Para JdbcTemplate

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
//    testCompileOnly 'org.projectlombok:lombok:1.18.30'
//    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}
//
//// Genera un fat JAR automáticamente
//bootJar {
//    archiveFileName = 'serverless.jar'
//
//}

shadowJar {
    archiveFileName = 'lambda.jar'
    mergeServiceFiles()
    dependencies {
        exclude(dependency('org.springframework.boot:spring-boot-starter-tomcat')) // Opcional para Lambda
    }
    manifest {
        attributes 'Main-Class': 'org.pucmm.practica.Main'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
